### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by 0x38** [pfarnach/magic-mirror#1]
Hi, many  thanks for this project, I really love it but is it possible to get a sample of the config.js file?

As is required on index.html

<script src="static/js/config.js"></script> 

by other side is it posible to change Fahrenheit to Celsius?

many thanks.

**Comment by pfarnach** [comment]
Sure, here you go:

```
var config = {
    weather_api_key: 'your_api_key_here',
    location: {
        latitude: 30,
        longitude: 45
    }
};
```

**Comment by 0x38** [comment]
many thanks!
it works!

 is it posible to change Fahrenheit to Celsius?

**Comment by pfarnach** [comment]
You can set celsius in a query parameter in your API call.  I'd recommend looking at the "Options" section of their docs and playing around a bit.

https://developer.forecast.io/docs/v2

Not having the code accessible right now, I'm guessing you'd append `?units=si` to the URL. Hope this helps

**Comment by 0x38** [comment]
Yes! thank you! works perfectly.
